import { MenuItem } from '@/types';

export const DEFAULT_VEG_ITEMS: MenuItem[] = [
  { id: 'v1',  name: 'Tomato Dal',                   category: 'veg', isActive: true, sortOrder: 1 },
  { id: 'v2',  name: 'Methi Chaman',                 category: 'veg', isActive: true, sortOrder: 2 },
  { id: 'v3',  name: 'Saag Paneer',                  category: 'veg', isActive: true, sortOrder: 3 },
  { id: 'v4',  name: 'Sambar',                       category: 'veg', isActive: true, sortOrder: 4 },
  { id: 'v5',  name: 'Paneer 65 Biryani',            category: 'veg', isActive: true, sortOrder: 5 },
  { id: 'v6',  name: 'Paneer 555 Biryani',           category: 'veg', isActive: true, sortOrder: 6 },
  { id: 'v7',  name: 'Gutti Vankaya Biryani',        category: 'veg', isActive: true, sortOrder: 7 },
  { id: 'v8',  name: 'Mylavaram Paneer Biryani',     category: 'veg', isActive: true, sortOrder: 8 },
  { id: 'v9',  name: 'Bezawada Paneer Biryani',      category: 'veg', isActive: true, sortOrder: 9 },
  { id: 'v10', name: 'Mushroom Masala',               category: 'veg', isActive: true, sortOrder: 10 },
  { id: 'v11', name: 'Mushroom Curry',                category: 'veg', isActive: true, sortOrder: 11 },
  { id: 'v12', name: 'Spinach Curry',                 category: 'veg', isActive: true, sortOrder: 12 },
  { id: 'v13', name: 'Vegetable Kurma',               category: 'veg', isActive: true, sortOrder: 13 },
  { id: 'v14', name: 'Kandhari Vegetables',           category: 'veg', isActive: true, sortOrder: 14 },
  { id: 'v15', name: 'Aloo Gobi',                    category: 'veg', isActive: true, sortOrder: 15 },
  { id: 'v16', name: 'Tindora Fry',                  category: 'veg', isActive: true, sortOrder: 16 },
  { id: 'v17', name: 'Karela Fry',                   category: 'veg', isActive: true, sortOrder: 17 },
  { id: 'v18', name: 'Okra Fry',                     category: 'veg', isActive: true, sortOrder: 18 },
  { id: 'v19', name: 'Potato Fry',                   category: 'veg', isActive: true, sortOrder: 19 },
  { id: 'v20', name: 'Cabbage Fry',                  category: 'veg', isActive: true, sortOrder: 20 },
  { id: 'v21', name: 'Eggplant Curry',               category: 'veg', isActive: true, sortOrder: 21 },
  { id: 'v22', name: 'Eggplant Bajji',               category: 'veg', isActive: true, sortOrder: 22 },
  { id: 'v23', name: 'Gobi 65',                      category: 'veg', isActive: true, sortOrder: 23 },
  { id: 'v24', name: 'Gobi Pakora',                  category: 'veg', isActive: true, sortOrder: 24 },
  { id: 'v25', name: 'Veg Pakora',                   category: 'veg', isActive: true, sortOrder: 25 },
  { id: 'v26', name: 'Paneer Pakora',                category: 'veg', isActive: true, sortOrder: 26 },
  { id: 'v27', name: 'Onion Samosa',                 category: 'veg', isActive: true, sortOrder: 27 },
  { id: 'v28', name: 'Onion Pakora',                 category: 'veg', isActive: true, sortOrder: 28 },
  { id: 'v29', name: 'Bonda',                        category: 'veg', isActive: true, sortOrder: 29 },
  { id: 'v30', name: 'Mysore Bonda',                 category: 'veg', isActive: true, sortOrder: 30 },
  { id: 'v31', name: 'Wada',                         category: 'veg', isActive: true, sortOrder: 31 },
  { id: 'v32', name: 'Punugulu',                     category: 'veg', isActive: true, sortOrder: 32 },
  { id: 'v33', name: 'Chitti Punugulu',              category: 'veg', isActive: true, sortOrder: 33 },
  { id: 'v34', name: 'French Fries',                 category: 'veg', isActive: true, sortOrder: 34 },
  { id: 'v35', name: 'Baby Corn',                    category: 'veg', isActive: true, sortOrder: 35 },
  { id: 'v36', name: 'Dry Baby Corn',                category: 'veg', isActive: true, sortOrder: 36 },
  { id: 'v37', name: 'Loose Baby Corn',              category: 'veg', isActive: true, sortOrder: 37 },
  { id: 'v38', name: 'Cut Mirchi',                   category: 'veg', isActive: true, sortOrder: 38 },
  { id: 'v39', name: 'Masala Papad',                 category: 'veg', isActive: true, sortOrder: 39 },
  { id: 'v40', name: 'Jeera Rice',                   category: 'veg', isActive: true, sortOrder: 40 },
  { id: 'v41', name: 'Tamarind Rice',                category: 'veg', isActive: true, sortOrder: 41 },
  { id: 'v42', name: 'Pulihara',                     category: 'veg', isActive: true, sortOrder: 42 },
  { id: 'v43', name: 'Curd Rice',                    category: 'veg', isActive: true, sortOrder: 43 },
  { id: 'v44', name: 'Kashmir Pulao',                category: 'veg', isActive: true, sortOrder: 44 },
  { id: 'v45', name: 'Paneer Fried Rice',            category: 'veg', isActive: true, sortOrder: 45 },
  { id: 'v46', name: 'Jackfruit Biryani',            category: 'veg', isActive: true, sortOrder: 46 },
  { id: 'v47', name: 'Oppu Curry',                   category: 'veg', isActive: true, sortOrder: 47 },
  { id: 'v48', name: 'Appadam Bajji',                category: 'veg', isActive: true, sortOrder: 48 },
  { id: 'v49', name: 'Snake Gourd Majjiga Charu',    category: 'veg', isActive: true, sortOrder: 49 },
  { id: 'v50', name: 'Maggiga Charu',                category: 'veg', isActive: true, sortOrder: 50 },
  { id: 'v51', name: 'Pottlakaya Perugu Chutney',   category: 'veg', isActive: true, sortOrder: 51 },
  { id: 'v52', name: 'Turia with Chana Dal',         category: 'veg', isActive: true, sortOrder: 52 },
  { id: 'v53', name: 'Turiya Chana Dal',             category: 'veg', isActive: true, sortOrder: 53 },
];

export const DEFAULT_NON_VEG_ITEMS: MenuItem[] = [
  { id: 'nv1',  name: 'Goat Curry',                  category: 'non-veg', isActive: true, sortOrder: 1 },
  { id: 'nv2',  name: 'Lamb Curry',                  category: 'non-veg', isActive: true, sortOrder: 2 },
  { id: 'nv3',  name: 'Apollo Fish',                 category: 'non-veg', isActive: true, sortOrder: 3 },
  { id: 'nv4',  name: 'Nellore Fish Curry',          category: 'non-veg', isActive: true, sortOrder: 4 },
  { id: 'nv5',  name: 'Gongura Shrimp Curry',        category: 'non-veg', isActive: true, sortOrder: 5 },
  { id: 'nv6',  name: 'Chintachiguru Shrimp Curry',  category: 'non-veg', isActive: true, sortOrder: 6 },
  { id: 'nv7',  name: 'Chicken Tikka Masala',        category: 'non-veg', isActive: true, sortOrder: 7 },
  { id: 'nv8',  name: 'Butter Chicken',              category: 'non-veg', isActive: true, sortOrder: 8 },
  { id: 'nv9',  name: 'Meat Balls Curry',            category: 'non-veg', isActive: true, sortOrder: 9 },
  { id: 'nv10', name: 'Tandoori Chicken',            category: 'non-veg', isActive: true, sortOrder: 10 },
  { id: 'nv11', name: 'Chicken Seekh Kabab',         category: 'non-veg', isActive: true, sortOrder: 11 },
  { id: 'nv12', name: 'Chicken Fry Curry',           category: 'non-veg', isActive: true, sortOrder: 12 },
  { id: 'nv13', name: 'Chicken 65 Biryani',          category: 'non-veg', isActive: true, sortOrder: 13 },
  { id: 'nv14', name: 'Chicken 555 Biryani',         category: 'non-veg', isActive: true, sortOrder: 14 },
  { id: 'nv15', name: 'Bezawada Chicken Biryani',    category: 'non-veg', isActive: true, sortOrder: 15 },
  { id: 'nv16', name: 'Mylavaram Chicken Biryani',   category: 'non-veg', isActive: true, sortOrder: 16 },
  { id: 'nv17', name: 'Chicken Mughlai Biryani',     category: 'non-veg', isActive: true, sortOrder: 17 },
  { id: 'nv18', name: 'Gongura Chicken Biryani',     category: 'non-veg', isActive: true, sortOrder: 18 },
  { id: 'nv19', name: 'Natukodi Pulusu',             category: 'non-veg', isActive: true, sortOrder: 19 },
  { id: 'nv20', name: 'Tandoori Chicken Biryani',    category: 'non-veg', isActive: true, sortOrder: 20 },
  { id: 'nv21', name: 'Chicken Dum Biryani',         category: 'non-veg', isActive: true, sortOrder: 21 },
];

export const DEFAULT_DESSERTS: MenuItem[] = [
  { id: 'd1',  name: 'Fruit Custard',               category: 'dessert', isActive: true, sortOrder: 1 },
  { id: 'd2',  name: 'Coconut Mousse',              category: 'dessert', isActive: true, sortOrder: 2 },
  { id: 'd3',  name: 'Gulab Jamun',                 category: 'dessert', isActive: true, sortOrder: 3 },
  { id: 'd4',  name: 'Kheer Badam',                 category: 'dessert', isActive: true, sortOrder: 4 },
  { id: 'd5',  name: 'Pineapple Kesari',            category: 'dessert', isActive: true, sortOrder: 5 },
  { id: 'd6',  name: 'Mango Mousse',                category: 'dessert', isActive: true, sortOrder: 6 },
  { id: 'd7',  name: 'Semiya Payasam',              category: 'dessert', isActive: true, sortOrder: 7 },
  { id: 'd8',  name: 'Carrot Halwa',                category: 'dessert', isActive: true, sortOrder: 8 },
  { id: 'd9',  name: 'Laddu',                       category: 'dessert', isActive: true, sortOrder: 9 },
  { id: 'd10', name: 'Mango Kesari',                category: 'dessert', isActive: true, sortOrder: 10 },
  { id: 'd11', name: 'Saggu Biyyam Semiya Payasam', category: 'dessert', isActive: true, sortOrder: 11 },
];

export const DEFAULT_ACCOMPANIMENTS: MenuItem[] = [
  { id: 'a1', name: 'Chutneys',    category: 'accompaniment', isDefault: true, isActive: true, sortOrder: 1 },
  { id: 'a2', name: 'Fryams',      category: 'accompaniment', isDefault: true, isActive: true, sortOrder: 2 },
  { id: 'a3', name: 'Salads',      category: 'accompaniment', isDefault: true, isActive: true, sortOrder: 3 },
  { id: 'a4', name: 'Naan',        category: 'accompaniment', isDefault: true, isActive: true, sortOrder: 4 },
  { id: 'a5', name: 'Tea',         category: 'accompaniment', isDefault: true, isActive: true, sortOrder: 5 },
  { id: 'a6', name: 'White Rice',  category: 'accompaniment', isDefault: true, isActive: true, sortOrder: 6 },
  { id: 'a7', name: 'Raita',       category: 'accompaniment', isDefault: true, isActive: true, sortOrder: 7 },
  { id: 'a8', name: 'Roti Chutney',category: 'accompaniment', isDefault: true, isActive: true, sortOrder: 8 },
];

export function getAllMenuItems() {
  return {
    veg: DEFAULT_VEG_ITEMS,
    nonVeg: DEFAULT_NON_VEG_ITEMS,
    desserts: DEFAULT_DESSERTS,
    accompaniments: DEFAULT_ACCOMPANIMENTS,
  };
}
